#!/bin/sh
set -eu

lb config noauto \
  --mode debian \
  --distribution trixie \
  --architectures amd64 \
  --binary-images iso-hybrid \
  --debian-installer live \
  --apt-recommends false \
  --archive-areas "main contrib non-free-firmware" \
  --bootappend-live "boot=live components quiet splash username=windra hostname=windra live-config.nox11autologin"
